---
abstract: 'SQLite Backend using DBI for Deeme'
author:
  - 'mudler <mudler@dark-lab.net>'
build_requires:
  Carp::Always: 0
  Test::More: 0
configure_requires:
  Module::Build::Tiny: 0.035
  perl: 5.008005
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.4, Dist::Zilla version 5.012, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Deeme-Backend-SQLite
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  DBD::SQLite: 0
  DBI: 0
  Deeme: 0
  Deeme::Backend::DBI: 0
  Deeme::Backend::Mango: 0
  Deeme::Obj: 0
  Deeme::Utils: 0
  feature: 0
resources:
  bugtracker: https://github.com/mudler/p5-Deeme-Backend-SQLite/issues
  homepage: https://github.com/mudler/p5-Deeme-Backend-SQLite
  repository: https://github.com/mudler/p5-Deeme-Backend-SQLite.git
version: 0.02
